### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by xfq** [KravisII/web_rubik_cube#2]
In [package.json](https://github.com/KravisII/web_rubik_cube/blob/131450ff7361e1cb718555cd8bbd338376ac5695/package.json#L10), this project seems to use the ISC license, but the license notice isn't in the source code or a seperate LICENSE/COPYING file. Please add it, thanks.

**Comment by KravisII** [comment]
Sure, I have changed license to _GNU General Public License v3.0_. And new license file is [here](https://github.com/KravisII/web_rubik_cube/blob/c3e74299d4928af110f2f5a0354239ce68f41270/LICENSE).
