### ISSUE TITLE
Add spacing

### ISSUE THREAD

**Issue by xfq** [KravisII/web_rubik_cube#3]
Please add spacing in the `alert` method of [texture.js](https://github.com/KravisII/web_rubik_cube/blob/131450ff7361e1cb718555cd8bbd338376ac5695/texture.js#L19). According to [Requirements for Chinese Text Layout § 3.2.2](https://www.w3.org/TR/clreq/#mixed_text_composition_in_horizontal_writing_mode):

> In principle, there is tracking or spacing between an adjacent Han character and Western character of up to one quarter of a Han character width, except at the line head or end.

Thanks!

**Comment by KravisII** [comment]
Fine, I will delete this file, because it's a example code copied from [here](https://github.com/newbieYoung/Threejs_rubik/blob/097a38409224890903e6345dc813271ac2052977/step2.html#L126).

**Comment by xfq** [comment]
Seems to be fixed by ab1ca4035c37d87bcb716355c3a59b6f6145ec71. Closing.
